modLoader="javafml" #mandatory
loaderVersion="[28,)"

[[mods]] #generate

modId="generate"
version="2.0-1.14"
displayName="Generate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/generate"
authors="MoxLotus"

# The description text for the mod (multi line!) (#mandatory)
description='''

'''

[[dependencies.generate]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.generate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
